# QuantFreedom Video - Feb 19, 2024 - Building a Trading Bot

In [13]:
# YT Video - https://youtu.be/ZqtJgyCR0Qo?si=UUSQ146qR5ML_ca7
# import libs
import os
import numpy as np
from strat import MACDandEMA

from quantfreedom.enums import *
from quantfreedom.helper_funcs import dl_ex_candles
from quantfreedom.simulate import run_df_backtest, or_backtest

np.set_printoptions(formatter={'float_kind': '{:0.2f}'.format})

from dotenv import load_dotenv
load_dotenv()
api_key = os.getenv('MFX_KEY')
api_secret = os.getenv('MFX_SECRET')

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [14]:
# Download candles frrom exchange
candles = dl_ex_candles(
  exchange='mufex',
  symbol='BTCUSDT',
  timeframe='15m',
  candles_to_dl=3000,
)
print(candles)

[[1708092000000.00 52488.50 52615.50 52190.00 52220.70 495.48]
 [1708092900000.00 52220.70 52246.70 51969.30 52201.70 431.25]
 [1708093800000.00 52201.70 52430.40 52131.80 52277.00 330.38]
 ...
 [1710789300000.00 67159.20 67449.50 67129.80 67387.90 149.97]
 [1710790200000.00 67387.90 67494.70 67180.90 67202.30 100.32]
 [1710791100000.00 67202.30 67315.30 66958.40 66977.70 129.72]]


In [9]:
# Use MACD strategy inside my strat script
macd_strat = MACDandEMA(
  long_short='long',
  ema_length=np.arange(100, 501, 100),
  fast_length=np.arange(10, 61, 10),
  macd_below=np.arange(0, 51, 25),
  signal_smoothing=np.arange(5, 16, 5),
  slow_length=np.arange(30, 121, 30)
)
print(macd_strat.indicator_settings_arrays.ema_length)

[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200 200 200 200 200 200 200 200 200 200 200 20

In [15]:
# Call entry/exit func from strat.py based off MACD signal
macd_strat.set_entries_exits_array(
  candles=candles,
  ind_set_index=0,
)
macd_strat.ema

array([nan, nan, nan, ..., 67733.11, 67722.60, 67707.85])

In [16]:
# Plot Strategy
macd_strat.plot_signals(candles=candles)

# Backtest